//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBike
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT_FULL_VW
    {
        public int ID { get; set; }
        public int RENT_TYPE_ID { get; set; }
        public int STORE_ID { get; set; }
        public decimal FEE_PER_DAY { get; set; }
        public decimal CONTRACT_AMOUNT { get; set; }
        public System.DateTime RENT_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public string PAY_FEE_MESSAGE { get; set; }
        public string NOTE { get; set; }
        public int REFERENCE_ID { get; set; }
        public string REFERENCE_NAME { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string ITEM_TYPE { get; set; }
        public string ITEM_LICENSE_NO { get; set; }
        public string SERIAL_1 { get; set; }
        public string SERIAL_2 { get; set; }
        public string DETAIL { get; set; }
        public string PHOTO_1 { get; set; }
        public string THUMBNAIL_PHOTO_1 { get; set; }
        public string PHOTO_2 { get; set; }
        public string THUMBNAIL_PHOTO_2 { get; set; }
        public string PHOTO_3 { get; set; }
        public string THUMBNAIL_PHOTO_3 { get; set; }
        public string PHOTO_4 { get; set; }
        public string THUMBNAIL_PHOTO_4 { get; set; }
        public string PHOTO_5 { get; set; }
        public string THUMBNAIL_PHOTO_5 { get; set; }
        public bool IS_BAD_CONTRACT { get; set; }
        public string SEARCH_TEXT { get; set; }
        public bool CONTRACT_STATUS { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string LICENSE_NO { get; set; }
        public string PHONE { get; set; }
        public Nullable<System.DateTime> LICENSE_RANGE_DATE { get; set; }
        public string LICENSE_RANGE_PLACE { get; set; }
        public string PERMANENT_RESIDENCE { get; set; }
        public string CURRENT_RESIDENCE { get; set; }
        public Nullable<System.DateTime> BIRTH_DAY { get; set; }
        public string EMAIL { get; set; }
        public byte[] PHOTO { get; set; }
        public bool IS_LOW_RECOVERABILITY { get; set; }
        public string REFERENCE_PHONE { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string CLASS_NAME { get; set; }
        public string ADDRESS { get; set; }
        public int CUS_CITY_ID { get; set; }
        public string STORE_NAME { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string RENT_TYPE_NAME { get; set; }
        public System.DateTime CLOSE_CONTRACT_DATE { get; set; }
        public string CONTRACT_NO { get; set; }
        public string IMPLEMENTER { get; set; }
        public string BACK_TO_DOCUMENTS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
