//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBike
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_FULL_VW
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public int CITY_ID { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public decimal START_CAPITAL { get; set; }
        public decimal CURRENT_CAPITAL { get; set; }
        public System.DateTime APPLY_DATE { get; set; }
        public decimal REVENUE_BEFORE_APPLY { get; set; }
        public decimal TOTAL_COST_BEFORE { get; set; }
        public decimal TOTAL_INVESMENT_BEFORE { get; set; }
        public System.DateTime REGISTER_DATE { get; set; }
        public bool ACTIVE { get; set; }
        public string NOTE { get; set; }
        public string SEARCH_TEXT { get; set; }
        public string CITY { get; set; }
    }
}
