//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBike
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPeriod
    {
        public int ID { get; set; }
        public int CONTRACT_ID { get; set; }
        public System.DateTime PAY_DATE { get; set; }
        public decimal AMOUNT_PER_PERIOD { get; set; }
        public bool STATUS { get; set; }
        public decimal ACTUAL_PAY { get; set; }
    }
}
