//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBike
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentBikeEntities : DbContext
    {
        public RentBikeEntities()
            : base("name=RentBikeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AccountPermission> AccountPermissions { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Contract> Contracts { get; set; }
        public DbSet<ContractHistory> ContractHistories { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<InOut> InOuts { get; set; }
        public DbSet<InOutType> InOutTypes { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<PayPeriod> PayPeriods { get; set; }
        public DbSet<ReferencePerson> ReferencePersons { get; set; }
        public DbSet<RentType> RentTypes { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<StoreFee> StoreFees { get; set; }
        public DbSet<CONTRACT_FULL_VW> CONTRACT_FULL_VW { get; set; }
        public DbSet<CONTRACT_HISTORY_FULL_VW> CONTRACT_HISTORY_FULL_VW { get; set; }
        public DbSet<INOUT_FULL_VW> INOUT_FULL_VW { get; set; }
        public DbSet<STORE_FULL_VW> STORE_FULL_VW { get; set; }
    }
}
