//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBike
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentType
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<bool> ISINCOME { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<bool> IS_CONTRACT { get; set; }
    }
}
