//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBike
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryPayFeeDaily
    {
        public int ID { get; set; }
        public int CONTRACT_ID { get; set; }
        public string CONTRACT_NO { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string PHONE { get; set; }
        public int RENT_TYPE_ID { get; set; }
        public string RENT_TYPE_NAME { get; set; }
        public System.DateTime PERIOD_DATE { get; set; }
        public decimal PAY_FEE { get; set; }
        public int PAY_TIME { get; set; }
        public string PAY_MESSAGE { get; set; }
        public int STORE_ID { get; set; }
        public string STORE_NAME { get; set; }
        public string NOTE { get; set; }
        public string SEARCH_TEXT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
